### ISSUE TITLE
[request] multiple version support (both open and save)

### ISSUE THREAD

**Issue by Tcll** [pycollada/pycollada#47] opened 2015-02-18 03:53 UTC
I understand 1.5.0 is being worked on, which is actually what brings me here...
code:

    dae = collada.Collada(StringIO(string(0)))
    print dae.geometries

results:

    importing FitPikachu00.dae 100% 
    Converting from import format...
    []
    Verifying data...
    Finalizing...
    Updating Viewer

reason:

    <COLLADA version="1.5.0" xmlns="http://www.collada.org/2008/03/COLLADASchema">

^ I was P'd when I found this out XD

but anyways, I'd like to request support for other major versions used with Blender24 (1.3.1 and 1.4.0)

I'm sure you guys are planning to eventually support all versions, but these are just some priorities. ;)

thanks :)

**Comment by Tcll** [comment] 2015-02-18 16:08
ok... maybe it's something I'm doing wrong... 141 is doing the exact same thing:

    importing FitPikachu00_141.dae 100%
    Converting from import format...
    5319
    <Collada geometries=0>
    Verifying data...
    Finalizing...
    Updating Viewer

geometries are still none... there should be 5...

code:

    f=StringIO(string(0))
    print f.read().count('\n')
    f.seek(0,0)
    dae = collada.Collada(f)
    print dae

**Comment by jterrace** [comment] 2015-02-18 16:28
Your file has 1.5 namespace:
http://www.collada.org/2008/03/COLLADASchema

The 1.4 namespace is:
http://www.collada.org/2005/11/COLLADASchema

**Comment by jterrace** [comment] 2015-02-18 16:28
pycollada doesn't support 1.5 and 1.4 together. There is a [1.5 branch](https://github.com/pycollada/pycollada/tree/collada15spec) but it's not being maintained. Closing as dupe of #23

**Closed** 2015-02-18 16:29 UTC

**Comment by Tcll** [comment] 2015-02-18 19:45
just did some technical work and even tried lxml

I'm not sure why neither XML parser can seem to find this:
FitPikachu00_141.dae line 173:

	<library_geometries>
		<geometry id="polygon0" name="polygon0">

code:

    dae = Collada(StringIO(string(0)))

    t = common.tag('library_geometries')
    #t = 'library_geometries' # tried this as well with no success
    print t
    print dae.xmlnode.findall(t)

results:

    importing FitPikachu00_141.dae 100%
    Converting from import format...
    {http://www.collada.org/2005/11/COLLADASchema}library_geometries
    []
    Verifying data...
    Finalizing...
    Updating Viewer

**Comment by Tcll** [comment] 2015-02-18 19:49
> Closing as dupe of #23

it's not a dupe as #23 doesn't request:
> (1.3.1 and 1.4.0)

**Comment by Tcll** [comment] 2015-02-18 19:52
> Your file has 1.5 namespace:

ok thanks :)

    <COLLADA version="1.4.1" xmlns="http://www.collada.org/2005/11/COLLADASchema">

results:

    importing FitPikachu00_141.dae 100%
    Converting from import format...
    {http://www.collada.org/2005/11/COLLADASchema}library_geometries
    [<Element '{http://www.collada.org/2005/11/COLLADASchema}library_geometries' at 0x29be8f0>]
    Verifying data...
Finalizing...
Updating Viewer

**Comment by jterrace** [comment] 2015-02-18 20:16
It's because of the namespace. Read up on namespaces in XML - the problem is that the `<tag2>` element in `<tag1 xmlns="foo"><tag2/></tag1>` vs `<tag1 xmlns="bar"><tag2/></tag1>` are actually *not* the same named element.

On option is to parse the namespace name up front and store it in class state. Then everywhere we currently use that static `tag()` function, use a class member tag function instead.
