### ISSUE TITLE
Reading the <skeleton> node

### ISSUE THREAD

**Issue by Crowfunder** [pycollada/pycollada#129] opened 2022-10-04 19:01 UTC
Is there any elegant way to read the `<skeleton>` node from `library_visual_scenes/visual_scene/node/instance_controller`  other than manually extracting it from instance_controller's xmlnode?

Or, at the very least, is there a way to directly access the node object mentioned in the aforementioned "skeleton" node from the controller's level?

**Comment by jterrace** [comment] 2022-10-15 14:25
You can access the raw node via the `.xmlnode` properties. But we don't have parsing support for 1.5.

**Comment by jterrace** [comment] 2022-10-15 14:26
Duplicate of #25

**Closed by jterrace** 2022-10-15 14:26 UTC
